### ISSUE TITLE
Parsing errors?

### ISSUE THREAD

**Issue by Xuerian** [VoiDGlitch/WarframeData#17]
See: https://github.com/VoiDGlitch/WarframeData/blob/157dd84fc413c4558dc303afa1ae77583ff6f646/MissionDecks.txt#L989

(And two other occurrences of "")

See also: https://github.com/VoiDGlitch/WarframeData/blob/157dd84fc413c4558dc303afa1ae77583ff6f646/MissionDecks.txt#L2818

(These links are to the current commit as of this ticket, instead of directly to head)

**Comment by VoiDGlitch** [comment]
1)             StoreItem=
		Rarity=COMMON
		Bias=0
		Atten=0
		UpgradeLevel=QA_LOW
		ItemCount=1
		DailyCooldown=False

You can see by this information that there is no localization path assigned to this item. Not a parsing error. Seems to be a path error from the game directly.

2) Does this Void Relic even still exist? Because Digital Extremes tends to leave unused content in their code, so this could be the case, unless you can show me otherwise?

**Comment by VoiDGlitch** [comment]
Update to the second issue.

One of my friends has informed me that this Void Relic is the LITH V2 RELIC. Will investigate on this parsing error.

**Comment by Xuerian** [comment]
It was the V2 relic, yes, as blame on the line shows.

The new relic system does not allow for any relics to be deleted unless no player has a single copy of the relic.
