### ISSUE TITLE
Mission Decks of non-endless mission types

### ISSUE THREAD

**Issue by MarioVX** [VoiDGlitch/WarframeData#6]
What happened to the mission decks of non-endless missions? When you took them out several weeks ago I thought it was only temporary, but in the more recent version they're still missing. They're really important. Have they become harder encrypted than the endless ones, or is this an oversight?

**Comment by VoiDGlitch** [comment]
Ever since the recent Star Chart re-work, some MissionDecks either are out of place of have been moved to the server. When I look at the local content, it says the MissionDecks still exist but there is no content in them. I have a feeling that Digital Extremes has made some MissionDecks server-side, because remember, my data is extracted straight from the application.
